FROM node:argon

ARG FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ARG FIREBASE_DATABASE_URL
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_STORAGE_BUCKET
ARG FIREBASE_MESSAGING_SENDER_ID

ENV FIREBASE_API_KEY $FIREBASE_API_KEY
ENV FIREBASE_AUTH_DOMAIN $FIREBASE_AUTH_DOMAIN
ENV FIREBASE_DATABASE_URL $FIREBASE_DATABASE_URL
ENV FIREBASE_PROJECT_ID $FIREBASE_PROJECT_ID
ENV FIREBASE_STORAGE_BUCKET $FIREBASE_STORAGE_BUCKET
ENV FIREBASE_MESSAGING_SENDER_ID $FIREBASE_MESSAGING_SENDER_ID

RUN mkdir /app
WORKDIR /app

COPY package.json /app
RUN npm install

COPY . /app
RUN npm run build:prod

EXPOSE 3000

CMD ["npm", "start"]
